### ISSUE TITLE
Error when samples are not removed automatically (remove auto-QC flagged) 

### ISSUE THREAD

**Issue by albacamino** [julimontoto/guanin#7]
I am using: 

- guanin==1.2.2
- Python==3.11.1
- Windows 11
I get this error: **ValueError: Length of values (33) does not match length of index (31)** when I try to execute the third step (Techinal normalization parameters) if during the second step I do not apply the option Remove auto-QC flagged, that is, if  I don't remove the samples, I always get that error. 

What can I do? 
Thank you in advance :)

**Comment by julimontoto** [comment]
Fixed in last versions.
